### PR TITLE
Update README.md

### LINKED ISSUE #37: Update README.md to explain the diff with 4.15rc2
Hi,

Now with the latest 4.15rc2 updates, it's a bit confusing to understand how to use ROCm.  What is required to get OpenCL working with 4.15rc2 for example?

What is the kfd situation currently?
There are comments in `README.md` saying things like "not in upstream".  These should be changed into "not in upstream as of <version>" because when I see that the README was updated in August I know that this is probably untrue, and if the information can't be trusted then it loses value.

### PR DESCRIPTION
**Pull request by alexanderkjeldaas**
Fixes #37

### CODE REVIEW

**Comment by kentrussell** [comment]
I'll be honest, the change seems redundant. 4.15rc2 > 3.19, so anything as of 3.19 would be unsupported. But if Greg or any tech leads want me to pull it in to the 1.7 release, I can. Or I can try to add an additional note saying that we're in the process of upstreaming but it isn't done yet.

**Comment by fxkamd** [comment]
I agree with Kent. The original statement continues to be true. Calling out a particular kernel RC version does not add any value IMO. We can update this comment once upstreaming is done and the ioctl ABI has been updated to match the new upstream.

**Comment by alexanderkjeldaas** [comment]
The problem with statements like that is that the user has no way of
judging whether it's a current or old statement, so it should be dated or
be in reference to some stable point in time.

**Comment by kentrussell** [comment]
I think it's fair to assume that it's current as of the publishing of the document. We'll be upstream soon enough, but this update will just end up causing more confusion than it helps, and is one more thing to try to remember for each kernel rebase

**Pull request closed without merging**
